---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "coredns.fullname" . }}
  labels: {{- include "coredns.labels" . | nindent 4 }}
data:
  Corefile: |-
    {{- include "coredns.corefile" . | nindent 4 }}
