---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coredns.fullname" . }}-tcp
  labels:
    {{- include "coredns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-tcp
      protocol: TCP
      name: dns-tcp
  selector:
    {{- include "coredns.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "coredns.fullname" . }}-udp
  labels:
    {{- include "coredns.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: {{ .Values.service.port }}
      targetPort: dns-udp
      protocol: UDP
      name: dns-udp
  selector:
    {{- include "coredns.selectorLabels" . | nindent 4 }}
