sources:
  - service
  - gateway-grpcroute
  - gateway-httproute
provider:
  name: webhook
  webhook:
    image:
      repository: externaldns-webhook
      tag: latest
    env:
      - name: WEBHOOK_API_ENDPOINT
        valueFrom:
          configMapKeyRef:
            name: webhook
            key: apiEndpoint
      - name: WEBHOOK_API_ID
        valueFrom:
          secretKeyRef:
            name: webhook-credentials
            key: id
      - name: WEBHOOK_API_SECRET
        valueFrom:
          secretKeyRef:
            name: webhook-credentials
            key: secret
      - name: WEBHOOK_ZONES
        valueFrom:
          configMapKeyRef:
            name: webhook
            key: zones
      - name: WEBHOOK_VERBOSE
        value: "true"
    # TODO
    # resources:
    livenessProbe:
      httpGet:
        path: /-/liveness
        port: 8888
    readinessProbe:
      httpGet:
        path: /-/readiness
        port: 8888
    # TODO
    # serviceMonitor:
