{{ if .Values.route.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  parentRefs:
    {{- toYaml .Values.route.parentRefs | nindent 4 }}
  {{- with .Values.route.hostname }}
  hostnames:
    - {{ . }}
  {{- end }}
  rules:
    - backendRefs:
      - name: {{ include "api.fullname" . }}
        port: {{ .Values.service.httpPort }}
      matches:
        - path:
            type: PathPrefix
            value: /
{{- end }}
