{{- with .Values.config.postgres.existingSecret.name }}
{{- else }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
stringData:
  postgresPassword: {{ quote .Values.config.postgres.password }}
{{- end }}
