baseURL = "https://sneakybugs.github.io/CoreWarden/"
title = "CoreWarden"
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

pygmentsUseClasses = true
theme = "satellite"

taxonomies = []

[outputs]
  home = ["HTML", "JSON"]

[params]
[params.seo]
  description = "CoreWarden is the Kubernetes-native ad-blocking DNS"
[params.icons]
  favicon = "images/favicon.svg"
