// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.24.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Record struct {
	ID         int32
	Zone       string
	Content    string
	Name       string
	IsWildcard bool
	Type       int32
	CreatedAt  pgtype.Timestamptz
	ModifiedOn pgtype.Timestamptz
	Comment    string
}
